language: java
jdk:
  openjdk8
  
addons:
  sonarcloud:
    organization: jpark131
    token: 56c4b5bad11022618be95871c168b7fedba3d024
    
script:
  - ant build
  - sonar-scanner
  
dist: trusty